brainbotdev/brainbot

- .isort.cfg
- main.py
Added isort config file and re-formatted `main.py`.
> Code format

- main.py
Just a few extra features including a list of commands and a BrainBot introduction 👍
> main.py update

- utils.py
Very minor seasonal change to BrainBot's username (temporary).
> October.py

- .all-contributorsrc
- .bumpversion.cfg
- README.md
- main.py
Moved command list to wiki: https://github.com/bsoyka/brainbot/wiki
> Commands list

- CONTRIBUTING.md
> Add contributing guidelines and code of conduct

- .all-contributorsrc
- .bumpversion.cfg
- README.md
- main.py
- utils.py
Pretty simple, but I think a lot of users would enjoy this. The cool down is shared with the "someone tell me to" auto response as they are somewhat similar.
> BrainBot repeater

- utils.py
Kindly add the tag ` hacktoberfest-accepted` when you accept? Thanks.
> Solved issue #31

- main.py
- requirements.txt
Shortened cool down as it seems to be a bit too long. Added translation function.
> Add translator and change cooldowns

- .all-contributorsrc
- .bumpversion.cfg
- README.md
- main.py
- requirements.txt
> Add a git pull command

- .gitignore
- brainbot.ini.example
- main.py
Issues  #38 
* read cooldowns from brainbot.ini
* add brainbot.ini.example
* add brainbot.ini in .gitignore
> #38 read cooldowns from brainbot.ini

- CONTRIBUTING.md
- dev-requirements.txt
Also added a dev dependencies file
> Contributing guidelines changes

- main.py
Very small 3 line fix when English is the given language.
> English fix

- main.py
- utils.py
I made these changes to accomodate user-specific cooldowns #1 . What do you think? 
* Change last_used in Cooldown to dict so it can store multiple last_used values
* Add optional username param in Cooldown run to fetch specific last_used values
* Pass the username in "Someone tell me to" autoresponse
> Make "someone tell me to" cooldown user-specific #1

- main.py
- requirements.txt
> Switch to Google Translate

- main.py
- requirements.txt
> NATO Phonetic Alphabet

- brainbot.ini.example
- main.py
Closes  #67 
Added dedicated settings for !phon and !repeat cooldowns, both of them have been added to "brainbot.ini.example".
> Added !phon and !repeat dedicated cooldowns

- main.py
Closes #66 
Added !emoticon command.
> Added !emoticon

- main.py
~~Closes #~~
- An issue was made and assigned to me by a maintainer before opening this pull request.
> Add latex command

- main.py
Replaces `!` in message with `\!` to stop the bot from triggering itself.
> !repeat injection fix

- brainbot.ini.example
- main.py
- requirements.txt
- utils.py
Closes #18 
Added !poll command, which handles voting through reactions.
Users now can create simple polls and vote on them through message reactions. I've also made scheduled poll ends through Ryver reminders (although it's still unsupported by Pyryver), tasks and notifications.
Some documentation can be found on code.
> Voting system (!poll command)

- main.py
> game end error
